---
title: "Histogram, frequency plots"
author: "Nithiyashri Jayashankar"
format: html
editor: visual
---

Libraries

```{r}
packages <- c("tidyverse", "here", "broom", "table1", "ggprism", "patchwork", "RColorBrewer")
install.packages(setdiff(packages, rownames(installed.packages())))

library("here")
library("tidyverse")
library("broom")
library("table1")
library("ggprism")
library("patchwork")
library("RColorBrewer")
```

```{r}
normalized <- normalized_counts |>
  select(where(is.numeric))
normalized_sums <- rowSums(normalized)
  
non_normalized<- count_data |> 
  select(where(is.numeric))
non_normalized_sums <-rowSums(non_normalized)

normalized_sums
non_normalized_sums
  
```

```{r}
joined = cbind(non_normalized_sums, normalized_sums)
```

i NEED HELP HERE TO PUT THE 2 PLOTS NEXT TO EACH OTHER SINCE PATCHWORKS IS NOT WORKING FOR SOME REASON FOR ME :(

```{r}
P1 <- ggplot(joined, aes(x=normalized_sums))+
  geom_histogram()+
  scale_x_log10()
P1
```

```{r}
P2 <- ggplot(joined, aes(x=non_normalized_sums))+
  geom_histogram()+
  scale_x_log10()
P2
```

```{r}
library(tibble)
count_data_new <- tibble::rownames_to_column(count_data, "gene")
normalized_counts <- normalized_counts |> select(gene, everything())

```

## Geom Density graphs:

```{r}
ggplot(full_data, aes(x=gene, fill = diagnosis)) +
  geom_density()
```
